name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      PORT: 3000
      APP_URL: http://localhost:3000
      MONGODB_URI: mongodb://localhost:27017/blogify_test
      JWT_SECRET: test_jwt_secret_for_ci
      SESSION_SECRET: test_session_secret_for_ci
      EMAIL_USERNAME: test_email_username_for_ci
      EMAIL_PASSWORD: test_email_password_for_ci
      EMAIL_FROM: test@mail.com
      CLOUDINARY_CLOUD_NAME: test_cloud_name_for_ci
      CLOUDINARY_API_KEY: test_cloudinary_api_key_for_ci
      CLOUDINARY_API_SECRET: test_cloudinary_api_secret_for_ci
      BREVO_SMTP_HOST: test_brevo_smtp_host_for_ci
      BREVO_SMTP_PORT: 587
      BREVO_SMTP_USER: test_brevo_smtp_user_for_ci
      BREVO_SMTP_PASS: test_brevo_smtp_pass_for_ci

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build

  # Deploy to Render.com
  deploy-render:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  # Build and push Docker image
  docker-build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/blogify:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/blogify:${{ github.sha }}
